version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./Project:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3307"
    environment:
      MYSQL_HOST: localhost
      MYSQL_DATABASE: dockdb #DB 이름
      MYSQL_USER: user #user name
      MYSQL_PASSWORD: test1234
      MYSQL_ROOT_PASSWORD: test1234
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  php:
    image: php:latest
    container_name: php
    volumes:
     - ./Project:/var/www/html
    ports: 
     - "9000:9000"
    command:
      - /bin/sh
      - -command
      - |
              echo "security.limit_extensions = .php .phtml .php3 .php4 .php5 .html .htm" >> /usr/local/etc/php-fpm.d/www.conf
              php-fpm

